version: '3.8'

services:
  message_broker:
    build:
      context: ./message_broker
    volumes:
      - sessions:/data
    expose:
      - 6379
  switchboard_operator:
    image: node:14
    ports:
      - '$SWITCHBOARD_PORT:$SWITCHBOARD_PORT'
    command: node app.js
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - SWITCHBOARD_SECRET_KEY=$SWITCHBOARD_SECRET_KEY
      - SWITCHBOARD_PORT=$SWITCHBOARD_PORT
      - CONCIERGE_URL=$CONCIERGE_URL
      - CONCIERGE_POSTBACK_SECRET_KEY=$CONCIERGE_POSTBACK_SECRET_KEY
      - REDISCLOUD_URL=$REDISCLOUD_URL

volumes:
  sessions:
  node_modules: